$configs = $HOME/.config/hypr


source= $configs/Keybinds.conf

source= $configs/Startup_Apps.conf

source= $configs/Enviroment_Variables.conf

source= $configs/WindowRules.conf

source= $configs/SystemSettings.conf 

source= $configs/monitors.conf

source= $configs/workspaces.conf


