windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}



windowrule{
    name = mpv opacity
    opaque = true
    match:class = mpv
}




windowrule {
    name = thunar rename
    float = yes
    center = yes
    stay_focused = on
    match:class = thunar
    match:title = ^(Rename .*)$
}

windowrule {
    name = thunar file move
    float = yes
    center = yes
    match:class = thunar
    match:title = File Operation Progress
}



windowrule {
    name = Pavucontrol
    float = yes
    center = yes
    size = 800 500
    stay_focused = on
    match:class = org.pulseaudio.pavucontrol
    match:title = Volume Control
}

windowrule {
    name = nwg-displays
    float = yes
    center = yes
    size = 1200 500
    match:class = nwg-displays
    match:title = nwg-displays
}


windowrule {
    name = nwg-look
    float = yes
    center = yes
    size = 800 500
    match:class = nwg-look
    match:title = nwg-look
}

windowrule {
    name = Bluetooth Applet
    float = yes
    center = yes
    size = 800 500
    match:class = blueman-manager
    match:title = Bluetooth Devices
}
